use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use crate::types::{AiTool, Stack};

/// Root configuration stored in `.agents/harn/config.toml`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    pub project: ProjectSection,
    pub tools: ToolsSection,
    pub init: InitSection,
    pub check: CheckSection,
    pub gc: GcSection,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectSection {
    pub name: String,
    pub created: String,
    pub harn_version: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolsSection {
    pub agents: Vec<AiTool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InitSection {
    pub stack: Stack,
    #[serde(default)]
    pub file_hashes: BTreeMap<String, String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CheckSection {
    pub required_files: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GcSection {
    pub stale_threshold_days: u32,
    #[serde(default)]
    pub ignore_paths: Vec<String>,
    #[serde(default)]
    pub mappings: Vec<GcMapping>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GcMapping {
    pub doc: String,
    pub code: Vec<String>,
}

/// Standard path to the config file relative to project root.
pub const CONFIG_REL_PATH: &str = ".agents/harn/config.toml";

impl Config {
    /// Read config from the standard location under `project_root`.
    pub fn load(project_root: &Path) -> Result<Self> {
        let path = config_path(project_root);
        let contents = fs::read_to_string(&path).with_context(|| {
            format!(
                "Could not read harn config at {}.\n\
                 Run `harn init` to create a harness, or use `--dir` to specify the project directory.",
                path.display()
            )
        })?;
        let config: Config = toml::from_str(&contents).with_context(|| {
            format!(
                "Invalid config at {}.\n\
                 Fix the TOML syntax or run `harn init --force` to regenerate.",
                path.display()
            )
        })?;
        Ok(config)
    }

    /// Write config to the standard location under `project_root`.
    pub fn save(&self, project_root: &Path) -> Result<()> {
        let path = config_path(project_root);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).with_context(|| {
                format!(
                    "Could not create config directory: {}. Check filesystem permissions.",
                    parent.display()
                )
            })?;
        }
        let contents = toml::to_string_pretty(self)
            .context("Failed to serialize config. This is a bug — please report it.")?;
        let header = "# harn configuration — generated by `harn init`\n\
                      # This file should be committed to version control.\n\n";
        fs::write(&path, format!("{header}{contents}")).with_context(|| {
            format!(
                "Could not write config to {}. Check filesystem permissions.",
                path.display()
            )
        })?;
        Ok(())
    }
}

pub fn config_path(project_root: &Path) -> PathBuf {
    project_root.join(CONFIG_REL_PATH)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_config() -> Config {
        Config {
            project: ProjectSection {
                name: "test-project".to_string(),
                created: "2026-04-03".to_string(),
                harn_version: env!("CARGO_PKG_VERSION").to_string(),
            },
            tools: ToolsSection {
                agents: vec![AiTool::Codex, AiTool::ClaudeCode],
            },
            init: InitSection {
                stack: Stack::Rust,
                file_hashes: BTreeMap::from([("AGENTS.md".to_string(), "abc123".to_string())]),
            },
            check: CheckSection {
                required_files: vec![
                    "AGENTS.md".to_string(),
                    "ARCHITECTURE.md".to_string(),
                    "docs/evaluation/criteria.md".to_string(),
                ],
            },
            gc: GcSection {
                stale_threshold_days: 14,
                ignore_paths: vec![],
                mappings: vec![],
            },
        }
    }

    #[test]
    fn config_roundtrip() {
        let config = sample_config();
        let serialized = toml::to_string_pretty(&config).unwrap();
        let deserialized: Config = toml::from_str(&serialized).unwrap();

        assert_eq!(deserialized.project.name, "test-project");
        assert_eq!(deserialized.tools.agents.len(), 2);
        assert_eq!(deserialized.init.stack, Stack::Rust);
        assert_eq!(
            deserialized.init.file_hashes.get("AGENTS.md").unwrap(),
            "abc123"
        );
        assert_eq!(deserialized.gc.stale_threshold_days, 14);
    }

    #[test]
    fn config_save_and_load() {
        let dir = tempfile::tempdir().unwrap();
        let config = sample_config();
        config.save(dir.path()).unwrap();

        let loaded = Config::load(dir.path()).unwrap();
        assert_eq!(loaded.project.name, "test-project");
        assert_eq!(loaded.init.stack, Stack::Rust);
    }

    #[test]
    fn config_load_missing_file() {
        let dir = tempfile::tempdir().unwrap();
        let result = Config::load(dir.path());
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("harn init"),
            "Error should suggest harn init: {err}"
        );
    }
}
